name: Python CI

on:
  push:
    branches:
      - main  # Trigger the action when there are changes pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger the action when a pull request is made to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest version of Ubuntu

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the repository code
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python environment
        with:
          python-version: 3.8  # Specify the Python version (adjust based on your requirements)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrades pip to the latest version
          pip install -r requirements.txt  # Installs required dependencies from your requirements.txt

      # Step 4: Run Snowpark Python Scripts
      - name: Run Snowpark Python Scripts
        run: |
          python harmonize_tomtom.py  # Add your script files to run
          python analytics_tomtom.py  # Add your script files to run
          python traffic_congestion_metrics.py  # Add your script files to run

      # Step 5: Commit changes (optional, if your scripts make changes)
      - name: Commit changes (if applicable)
        run: |
          git config --global user.name "madhura-adadande"  # Set your GitHub username
          git config --global user.email "adadande.m@northeastern.edu"  # Set your email address
          git add .  # Add all changes to git
          git commit -m "Run Snowpark Python scripts via GitHub Actions"  # Commit the changes
          git push  # Push the changes back to the repository

